export const tasks = [
  {
    status: 'Not Started',
    title: 'For Loop with Arrays',
    difficulty: 'Easy',
    solution: 'Use a standard for loop to iterate and push items.',
    description: 'Iterate over an array using a traditional for loop to perform operations on each element.',
  },
  {
    status: 'In Progress',
    title: 'Filter Array Elements',
    difficulty: 'Medium',
    solution: 'Use Array.filter() with a condition function.',
    description: 'Filter elements from an array based on a provided predicate function.',
  },
  {
    status: 'Completed',
    title: 'Map Array to New Values',
    difficulty: 'Easy',
    solution: 'Use Array.map() to return transformed items.',
    description: 'Transform each element in an array into a new array using a mapping function.',
  },
  {
    status: 'Not Started',
    title: 'Reduce Array to Single Value',
    difficulty: 'Hard',
    solution: 'Use Array.reduce() with accumulator logic.',
    description: 'Aggregate array values into a single output using the reduce method.',
  },
  {
    status: 'In Progress',
    title: 'Nested Loops for Matrix',
    difficulty: 'Medium',
    solution: 'Use two nested for loops to access matrix elements.',
    description: 'Traverse a two-dimensional array (matrix) with nested loops.',
  }, {
    status: 'Not Started',
    title: 'For Loop with Arrays',
    difficulty: 'Easy',
    solution: 'Use a standard for loop to iterate and push items.',
    description: 'Iterate over an array using a traditional for loop to perform operations on each element.',
  },
  {
    status: 'In Progress',
    title: 'Filter Array Elements',
    difficulty: 'Medium',
    solution: 'Use Array.filter() with a condition function.',
    description: 'Filter elements from an array based on a provided predicate function.',
  },
  {
    status: 'Completed',
    title: 'Map Array to New Values',
    difficulty: 'Easy',
    solution: 'Use Array.map() to return transformed items.',
    description: 'Transform each element in an array into a new array using a mapping function.',
  },
  {
    status: 'Not Started',
    title: 'Reduce Array to Single Value',
    difficulty: 'Hard',
    solution: 'Use Array.reduce() with accumulator logic.',
    description: 'Aggregate array values into a single output using the reduce method.',
  },
  {
    status: 'In Progress',
    title: 'Nested Loops for Matrix',
    difficulty: 'Medium',
    solution: 'Use two nested for loops to access matrix elements.',
    description: 'Traverse a two-dimensional array (matrix) with nested loops.',
  },
]
