name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # ⚠️  Benötigt Repository-Secret „AZURE_STATIC_WEB_APPS_API_TOKEN“
      - name: Build & Deploy to Azure Static Web Apps
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_HILL_0AE627F03 }}

          #### Build-Konfiguration ####
          app_location: 'app' # React-Projekt mit package.json
          output_location: 'build' # Ordner nach `npm run build`
          api_location: '' # Azure-Functions-Ordner (optional)
          #### Ende Build-Konfiguration ####

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Remove PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: 'close'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_HILL_0AE627F03 }}
